apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::157670566394:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1AESHCZ52W3GV
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::157670566394:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-11-15T09:16:41Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "2222"
  uid: 93ae7317-825e-4f58-8241-c95953ddc6f6
